src/HVG/ExchangeBundle/Form/Type/TicketStatusType.php
<?php

namespace HVG\ExchangeBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class TicketStatusType extends AbstractType
{
    private $ticketstatuses;

    public function __construct(array $ticketstatuses)
    {
        $this->ticketstatuses = $ticketstatuses;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'choices' => array_flip($this->ticketstatuses),
            'choices_as_values' => true,
        ));
    }

    public function getParent()
    {
        return ChoiceType::class;
    }

    public function getName()
    {
        return 'ticket_status';
    }

}

src/HVG/ExchangeBundle/Controller/TicketZoneController.php
<?php

namespace HVG\ExchangeBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use HVG\SystemBundle\Entity\Community;
use HVG\SystemBundle\Entity\UnitGroup;
use HVG\SystemBundle\Entity\Unit;
use HVG\SystemBundle\Entity\Ticket;
use HVG\SystemBundle\Entity\TicketAction;

use HVG\ExchangeBundle\Form\TicketType;
use HVG\ExchangeBundle\Form\TicketActionType;
use HVG\ExchangeBundle\Form\StatusType;

class TicketZoneController extends Controller
{
    public function indexAction(Request $request, $status = null, Community $community = null, UnitGroup $unitgroup = null, Unit $unit = null)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();

        $communities = $em->getRepository('HVGSystemBundle:Community')->findAll();
        $unitgroups = $em->getRepository('HVGSystemBundle:UnitGroup')->findByCommunity($community);
        $units = $em->getRepository('HVGSystemBundle:Unit')->findByUnitgroup($unitgroup);

        $sort = $request->query->has('sort') ? $request->query->get('sort') : 'updatedAt';
        $direction = $request->query->has('direction') ? $request->query->get('direction') : 'DESC';

        $tickets = $em->getRepository('HVGSystemBundle:Ticket')->findByUserZone($status, $community, $unitgroup, $unit, $sort, $direction, $user);

        $paginator = $this->get('knp_paginator');
        $tickets = $paginator->paginate($tickets, $request->query->getInt('page', 1), 100);

        $ticketNewForm = null;
        if($unit) {
            $ticket = new Ticket();
            $ticketNewForm = $this->createNewTicketForm($ticket, $unit)->createView();
        }

        return $this->render('HVGExchangeBundle:TicketZone:index.html.twig', array(
            'communities' => $communities,
            'unitgroups' => $unitgroups,
            'units' => $units,
            'status' => $status,
            'community' => $community,
            'unitgroup' => $unitgroup,
            'unit' => $unit,
            'tickets' => $tickets,
            'direction' => $direction,
            'sort' => $sort,
            'ticketNewForm' => $ticketNewForm,
        ));
    }

    public function showAction(Ticket $ticket)
    {
        $em = $this->getDoctrine()->getManager();

        $user = $this->getUser();
        $status = $ticket->getStatus();
        $unit = $ticket->getUnit();
        $unitgroup = $unit->getUnitGroup();
        $community = $unit->getCommunity();

        $ticketActions = $em->getRepository('HVGSystemBundle:TicketAction')->findByTicket(array('id' => $ticket->getId()), array('createdAt' => 'DESC'));

        $ticketAction = new TicketAction();
        $ticketActionForm = $this->createTicketActionForm($ticket, $ticketAction);
        $ticketLiabilityForm = $this->createTicketLiabilityForm($ticket);
        $ticketStatusChangeForm = $this->createTicketStatusChangeForm($ticket);

        return $this->render('HVGExchangeBundle:TicketZone:show.html.twig', array(
            'status' => 0,
            'community' => $community,
            'unitgroup' => $unitgroup,
            'unit' => $unit,
            'ticket' => $ticket,
            'ticketActions' => $ticketActions,
            'ticketActionForm' => $ticketActionForm->createView(),
            'ticketLiabilityForm' => $ticketLiabilityForm->createView(),
            'ticketStatusChangeForm' => $ticketStatusChangeForm->createView(),
        ));
    }

    private function createNewTicketForm(Ticket $ticket, Unit $unit)
    {
        return $this->createForm('HVG\ExchangeBundle\Form\TicketType', $ticket, array(
            'action' => $this->generateUrl('exchange_ticketzone_new', array('unit' => $unit->getId())),
            'unit' => $unit,
        ));
    }

    public function newAction(Request $request, Unit $unit)
    {
        $user = $this->getUser();

        $ticket = new Ticket();
        $ticketNewForm = $this->createNewTicketForm($ticket, $unit);
        $ticketNewForm->handleRequest($request);
        if ($ticketNewForm->isSubmitted()) {
            if($ticketNewForm->isValid()) {
                $ticketAction = new TicketAction();
                $ticketAction->setTicket($ticket);
                $ticketAction->setDescription('Ticket Creado.');
                $ticketAction->setUser($user);
                $ticket->setUser($user);
                $ticket->setUnit($unit);
                $ticket->setStatus(1);
                $em = $this->getDoctrine()->getManager();
                $em->persist($ticket);
                $em->persist($ticketAction);
                $em->flush();
                $email = $ticket->getContactEmail();
                if($email) {
                    $message = new \Swift_Message($ticket->getUnit()->getCommunity() . ' - Ticket ' . $ticket->getId());
                    $message->setFrom('orion@hvg.cl', 'HVG Administraciones');
                    $message->setTo($email);
                    $message->setEncoder(\Swift_Encoding::get8BitEncoding());
                    $message->setBody($this->renderView('HVGExchangeBundle:TicketEmail:new.html.twig', array('ticket' => $ticket)), 'text/html');
                    $this->get('mailer')->send($message);
                }

                return $this->redirect($this->generateUrl('exchange_ticketzone_index', array(
                    'status' => 0,
                    'community' => $unit->getCommunity()->getId(),
                    'unitgroup' => $unit->getUnitGroup()->getId(),
                    'unit' => $unit->getId(),
                )));
            }
        }
        $unitgroup = $unit->getUnitGroup();
        $community = $unit->getCommunity();
        return $this->render('HVGExchangeBundle:TicketZone:new.html.twig', array(
            'status' => 0,
            'community' => $community,
            'unitgroup' => $unitgroup,
            'unit' => $unit,
            'ticketNewForm' => $ticketNewForm->createView(),
        ));
    }

    public function takeAction(Ticket $ticket)
    {
        $user = $this->getUser();

        $ticket->setLiability($user);
        $ticket->setStatus(2);

        $ticketAction = new TicketAction();
        $ticketAction->setTicket($ticket);
        $ticketAction->setUser($user);
        $ticketAction->setDescription('Ticket asignado a ' . $user->getPerson());

        $em = $this->getDoctrine()->getManager();
        $em->persist($ticket);
        $em->persist($ticketAction);
        $em->flush();

        return $this->redirect($this->generateUrl('exchange_ticketzone_show', array('ticket' => $ticket->getId())));
    }

    public function releaseAction(Ticket $ticket)
    {
        $user = $this->getUser();

        $ticket->setLiability(null);
        $ticket->setStatus(4);

        $ticketAction = new TicketAction();
        $ticketAction->setTicket($ticket);
        $ticketAction->setUser($user);
        $ticketAction->setDescription('Ticket Liberado por ' . $user->getPerson());

        $em = $this->getDoctrine()->getManager();
        $em->persist($ticket);
        $em->persist($ticketAction);
        $em->flush();

        return $this->redirect($this->generateUrl('exchange_ticketzone_show', array('ticket' => $ticket->getId())));
    }

    private function createEditForm(Ticket $ticket)
    {
        return $this->createForm('HVG\ExchangeBundle\Form\TicketType', $ticket, array(
            'action' => $this->generateUrl('exchange_ticketzone_edit', array('ticket' => $ticket->getId())),
            'unit' => $ticket->getUnit(),
        ));
    }

    public function editAction(Request $request, Ticket $ticket)
    {
        $user = $this->getUser();
        $unit = $ticket->getUnit();
        $editForm = $this->createEditForm($ticket);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted()) {
            if($editForm->isValid()) {
                $ticketAction = new TicketAction();
                $ticketAction->setTicket($ticket);
                $ticketAction->setDescription('Ticket Editado.');
                $ticketAction->setUser($user);

                $em = $this->getDoctrine()->getManager();
                $em->persist($ticket);
                $em->persist($ticketAction);
                $em->flush();

                return $this->redirect($this->generateUrl('exchange_ticketzone_show', array('ticket' => $ticket->getId())));
            }
        }

        $unitgroup = $unit->getUnitGroup();
        $community = $unit->getCommunity();
        return $this->render('HVGExchangeBundle:TicketZone:edit.html.twig', array(
            'status' => $ticket->getStatus(),
            'community' => $community,
            'unitgroup' => $unitgroup,
            'unit' => $unit,
            'ticket' => $ticket,
            'editForm' => $editForm->createView(),
        ));

    }

    private function createTicketActionForm(Ticket $ticket, TicketAction $ticketAction)
    {
        return $this->createForm('HVG\ExchangeBundle\Form\TicketActionType', $ticketAction, array(
            'action' => $this->generateUrl('exchange_ticketzone_action', array('ticket' => $ticket->getId())),
        ));
    }

    public function actionAction(Request $request, Ticket $ticket)
    {
        $ticketAction = new TicketAction();
        $ticketActionForm = $this->createTicketActionForm($ticket, $ticketAction);
        $ticketActionForm->handleRequest($request);
        if ($ticketActionForm->isSubmitted()) {
            if($ticketActionForm->isValid()) {
                $oldStatus = $ticket->getStatus();
                $ticket->setStatus(3);
                $ticketAction->setTicket($ticket);

src/HVG/ExchangeBundle/Resources/views/TicketZone/aside.html.twig
{% block aside %}
<div class="row">
    <nav class="sidebar-nav navbar-collapse collapse" id="sidebar">
        {{ knp_menu_render('HVGExchangeBundle:TicketZoneBuilder:sideMenu', {'currentClass': 'active', 'ancestorClass': 'active', 'leaf_class': 'leaf'}) }}
        <p></p>
    </nav>
</div>
{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/edit.html.twig
{% extends 'HVGExchangeBundle:TicketZone:layout.html.twig' %}

{% set translation_domain = 'HVGExchangeBundle' %}

{% trans_default_domain translation_domain %}

{% block title %}{{ 'ticket.index.title'|trans }}{% endblock %}

{% block ticket %}
    <div class="row" id="page-edit">
        <div class="col-xs-12">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h1 class="panel-title">{{ 'ticket.edit.title'|trans }}</h1>
                </div>
                <div class="panel-body">
                    {{ form_start(editForm, { 'style': 'horizontal' }) }}
                        {{ form_widget(editForm) }}
                        <div class="form-group"><div class="col-lg-offset-4 col-lg-8">
                            <button type="submit" class="btn btn-success">{{ icon('edit fa-fw') }}&nbsp;{{ 'ticket.edit.submit'|trans }}</button>
                        </div></div>
                    {{ form_end(editForm) }}
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-edit -->

{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/finder.html.twig
{% block finder %}
    {% set translation_domain = 'HVGExchangeBundle' %}{% trans_default_domain translation_domain %}
    <div class="row" id="selector">
        <div class="col-md-12">
            <ul class="nav nav-pills">
                {#}<li class="active"><a href="{{ path('exchange_ticketzone_index', {'status' : status}) }}">{{ icon('home fa-fw') }}&nbsp;{{ 'ticket.index.home'|trans }}</a></li>{#}
                {% if community %}<li class="active"><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : community.id}) }}">{{ community.name }}</a></li>{% endif %}
                {% if unitgroup %}<li class="active"><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : community.id, 'unitgroup' : unitgroup.id}) }}">{{ unitgroup.name }}</a></li>{% endif %}
                {% if unit %}<li class="active"><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : community.id, 'unitgroup' : unitgroup.id, 'unit' : unit.id}) }}">{{ unit.name }}</a></li>{% endif %}
                {% if ticket is defined %}<li class="active"><a href="{{ path('exchange_ticketzone_show', {'ticket' : ticket.id}) }}">Ticket {{ ticket.id }}</a></li>{% endif %}
            </ul>
            {% if community %}<p></p>{% endif %}
        </div>
    </div>
    <div class="row" id="finder">
        <div class="col-md-12">
        {% if not community %}{% if communities is not empty %}
            <ul class="nav nav-pills">
                {% for current in communities %}
                    <li {% if current == community %}class="active"{% endif %}><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : current.id}) }}">{{ current.name }}</a></li>
                {% endfor %}
            </ul>
            <p></p>
        {% endif %}{% endif %}
        {% if not unitgroup %}{% if unitgroups is not empty %}
            <ul class="nav nav-pills">
                {% for current in unitgroups %}
                    <li {% if current == unitgroup %}class="active"{% endif %}><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : community.id, 'unitgroup' : current.id}) }}">{{ current.name }}</a></li>
                {% endfor %}
            </ul>
            <p></p>
        {% endif %}{% endif %}
        {% if not unit %}{% if units is not empty %}
            <ul class="nav nav-pills">
                {% for current in units %}
                    <li {% if current == unit %}class="active"{% endif %}><a href="{{ path('exchange_ticketzone_index', {'status' : status, 'community' : community.id, 'unitgroup' : unitgroup.id, 'unit' : current.id}) }}">{{ current.name }}</a></li>
                {% endfor %}
            </ul>
            <p></p>
        {% endif %}{% endif %}
        </div>
    </div>
    <!-- /#finder -->
{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/index.html.twig
{% extends 'HVGExchangeBundle:TicketZone:layout.html.twig' %}

{% set translation_domain = 'HVGExchangeBundle' %}

{% trans_default_domain translation_domain %}

{% block title %}{{ 'ticket.index.title'|trans }}{% endblock %}

{% block ticket %}
    <div class="row" id="page-list">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">{{ 'ticket.index.list'|trans }}</h1>
                </div>
                <div class="table-responsive">
                    <table class="records_list table table-striped table-hover">
                        <thead>
                            <tr>
                                {#}
                                <th style="min-width: 120px;">
                                    <div class="btn-group"><a href="#" class="btn btn-xs btn-default disabled">{{ icon('search fa-fw') }}</a></div>
                                    <div class="btn-group"><a href="#" class="btn btn-xs btn-default disabled">{{ icon('edit fa-fw') }}</a></div>
                                    <div class="btn-group"><a href="#" class="btn btn-xs btn-default disabled">{{ icon('times fa-fw') }}</a></div>
                                </th>
                                {#}
                                <th><div class="btn-group"><a href="#" class="btn btn-xs btn-default disabled">{{ icon('search fa-fw') }}</a></div></th>
                                <th>{{ knp_pagination_sortable(tickets, 'ticket.form.id'|trans, 'id') }}{% if sort == 'id' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                                <th>{{ knp_pagination_sortable(tickets, 'ticket.form.ticketstatus'|trans, 'ticketstatus') }}{% if sort == 'ticketstatus' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                                <th>{{ knp_pagination_sortable(tickets, 'ticket.form.unit'|trans, 'unit') }}{% if sort == 'unit' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                                <th>{{ knp_pagination_sortable(tickets, 'ticket.form.zone'|trans, 'zone') }}{% if sort == 'zone' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                                <th>{{ knp_pagination_sortable(tickets, 'ticket.form.liability'|trans, 'liability') }}{% if sort == 'liability' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                                <th class="col-md-5">{{ 'ticket.form.description'|trans }}</th>
                                <th style="min-width: 200px;">{{ knp_pagination_sortable(tickets, 'ticket.form.updatedAt'|trans, 'updatedAt') }}{% if sort == 'updatedAt' %}{% if direction == 'desc' %}{{ icon('caret-down') }}{% else %}{{ icon('caret-up') }}{% endif %}{% endif %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ticket in tickets %}
                            <tr>
                                {#}
                                <td>
                                    <div class="btn-group"><a href="{{ path('exchange_ticketzone_show', {'ticket' : ticket.id}) }}" class="btn btn-xs btn-default">{{ icon('search fa-fw') }}</a></div>
                                    <div class="btn-group"><a href="{{ path('exchange_ticketzone_edit', {'ticket' : ticket.id}) }}" class="btn btn-xs btn-warning">{{ icon('edit fa-fw') }}</a></div>
                                    <div class="btn-group"><a href="{{ path('exchange_ticketzone_delete', {'ticket' : ticket.id}) }}" class="btn btn-xs btn-danger">{{ icon('times fa-fw') }}</a></div>
                                </td>
                                {#}
                                <td><div class="btn-group"><a href="{{ path('exchange_ticketzone_show', {'ticket' : ticket.id}) }}" class="btn btn-xs btn-default">{{ icon('search fa-fw') }}</a></div></td>
                                <td>{% if ticket.id %}{{ ticket.id }}{% endif %}</td>
                                <td>{% if ticket.status %}<span class="label label-info">{{ ticketstatuses[ticket.status] }}</span>{% endif %}</td>
                                <td>{% if ticket.unit %}<span class="label label-primary">{{ ticket.unit.community.name }}</span>&nbsp;<span class="label label-primary">{{ ticket.unit.unitgroup.name }}</span>&nbsp;<span class="label label-primary">{{ ticket.unit.name }}</span>{% endif %}</td>
                                <td>{% if ticket.zone %}{{ ticket.zone.name }}{% endif %}</td>
                                <td>{% if ticket.liability %}{{ ticket.liability.person }}{% endif %}</td>
                                <td>{% if ticket.description %}{{ ticket.description }}{% endif %}</td>
                                <td>{% if ticket.updatedAt %}<span class="fa fa-calendar-o fa-fw" data-toggle="tooltip" data-placement="left" title="{{ ticket.updatedAt|localizeddate('full', 'full', 'es_ES', 'America/Santiago', "dd LLLL y - HH:mm") }}"></span>&nbsp;{{ ticket.updatedAt|ago }}{% endif %}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-list -->

    <div id="page-modal">
        {% if unit %}
        <div class="modal fade" id="modalTicketNew" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">{{ icon('times') }}</button>
                        <h4 class="modal-title" id="myModalLabel">{{ 'ticket.new.title'|trans }}</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-xs-12">
                                {{ form_start(ticketNewForm, { 'style': 'horizontal' }) }}
                                    {{ form_widget(ticketNewForm) }}
                                    <div class="form-group"><div class="col-lg-offset-4 col-lg-8">
                                        <button type="submit" class="btn btn-primary">{{ icon('check fa-fw') }}&nbsp;{{ 'ticket.new.submit'|trans }}</button>
                                    </div></div>
                                {{ form_end(ticketNewForm) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
    <!-- /#page-modal -->

{% endblock %}

{% block javascript %}<script type="text/javascript">$(function () { $('[data-toggle="tooltip"]').tooltip() })</script>{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/layout.html.twig
{% extends 'HVGExchangeBundle:Base:layout.html.twig' %}
{% use 'HVGExchangeBundle:Base:header.html.twig' %}
{% use 'HVGExchangeBundle:TicketZone:aside.html.twig' %}
{% use 'HVGExchangeBundle:TicketZone:finder.html.twig' %}
{% use 'HVGExchangeBundle:TicketZone:tools.html.twig' %}

{% block exchange %}
    {% block finder %}{{ parent() }}{% endblock %}
    {% block tools %}{{ parent() }}{% endblock %}
    {% block ticketzone %}{% endblock %}
{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/new.html.twig
{% extends 'HVGExchangeBundle:TicketZone:layout.html.twig' %}

{% set translation_domain = 'HVGExchangeBundle' %}

{% trans_default_domain translation_domain %}

{% block title %}{{ 'ticket.index.title'|trans }}{% endblock %}

{% block ticket %}
    <div class="row" id="page-new">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title">{{ 'ticket.new.title'|trans }}</h1>
                </div>
                <div class="panel-body">
                    {{ form_start(ticketNewForm, { 'style': 'horizontal' }) }}
                        {{ form_widget(ticketNewForm) }}
                        <div class="form-group"><div class="col-lg-offset-4 col-lg-8">
                            <button type="submit" class="btn btn-primary">{{ icon('check fa-fw') }}&nbsp;{{ 'ticket.new.submit'|trans }}</button>
                        </div></div>
                    {{ form_end(ticketNewForm) }}
                </div>
            </div>
        </div>
    </div>
    <!-- /#page-new -->

{% endblock %}

src/HVG/ExchangeBundle/Resources/views/TicketZone/tools.html.twig
{% block tools %}
    {% trans_default_domain 'HVGExchangeBundle' %}
    <div class="row" id="tabs">
        <div class="col-md-12">
        {% if ticket is defined %}
            <div class="btn-toolbar">
                <div class="btn-group"><a href="{{ path('exchange_ticket_take', {'ticket' : ticket.id}) }}" class="btn btn-success">{{ icon('arrow-down fa-fw') }}&nbsp;{{ 'ticket.take.link'|trans }}</a></div>
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalTicketStatusChange">{{ icon('flag fa-fw') }}&nbsp;{{ 'ticket.status.link'|trans }}</button>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalTicketAction">{{ icon('cog fa-fw') }}&nbsp;{{ 'ticket.action.link'|trans }}</button>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modalTicketLiability">{{ icon('user fa-fw') }}&nbsp;{{ 'ticket.liability.link'|trans }}</button>
            </div>
            <p></p>
        {% elseif unit %}
            <div class="btn-toolbar">
                <div class="btn-group">
                    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modalTicketNew">{{ icon('plus fa-fw') }}&nbsp;{{ 'ticket.new.link'|trans }}</button>
                    {#}<a href="{{ path('exchange_ticket_new', {'unit' : unit.id}) }}" class="btn btn-success">{{ icon('plus fa-fw') }}&nbsp;{{ 'ticket.new.link'|trans }}</a>{#}
                </div>
            </div>
            <p></p>
        {% endif %}
        </div>
    </div>
    <!-- /#unit-tab -->
{% endblock %}